### ISSUE TITLE
MDF cut function 

### ISSUE THREAD

**Issue by hongjiaoptim** [danielhrisca/asammdf#101]
Dear developer:
     I want to use the cut function in class MDF. 
def cut(self, start=None, stop=None, whence=0, version=None, memory=None):
   and after cut ,the curve of mdf file signals move left with ‘start’ time in x axis (and the start time of the curve is  zero).
  Thank you for you work!

**Comment by danielhrisca** [comment]
Hello @hongjiaoptim ,

can you share the code snippet that you use and some screenshots to better show the problem?

**Comment by danielhrisca** [comment]
@hongjiaoptim 
are you still dealing with this issue?

**Comment by nos86** [comment]
Hello Daniel,
I don't know if my need is the same of @hongjiaoptim; at least the topic is the same.

I opened an MDF file and using the `cut` function I have obtained the reduced MDF file.
Now, I'd like to move the timestamps of each channel in order to start from zero, in order to save the new MDF file as a regular file with no time offset.

Thanks in advance,
Salvo

**Comment by danielhrisca** [comment]
Hello Salvo,

I will have a look at this. My plan is to focus more on the Py3 branch so I would first implemented there.

**Comment by danielhrisca** [comment]
@hongjiaoptim @nos86 
Please have a try with the development branch code: the argument _time_from_zero_ of _cut_ method should give the expected result.

**Comment by danielhrisca** [comment]
please re-open if the latest release does not work (5.1.1 at this time)
