### ISSUE TITLE
question about the channelgroup

### ISSUE THREAD

**Issue by HuixuanGan** [danielhrisca/asammdf#1011]
We are using the asammdf to extract the data from mf4 files and we got several csv files, each one is a channelgroup. Yet we are confused about the reason for this spliting, can anyone explain us what is the definition of this channel group?

Thank you!

**Comment by danielhrisca** [comment]
A channel group contains channels that have have the same time stamps (they are sampled at the same time during the recording of the measurement, usually because they come from the same physical device). 

To get a single CSV file you have to select the option `Single time base` from the GUI. The single time base is obtained by doing the union of all time bases from the channel groups, and the channels are interpolated using this single time base.

**Comment by HuixuanGan** [comment]
Thank you, it solved my problem!
