### ISSUE TITLE
Comparison mode plots strait lines when signals have text_values

### ISSUE THREAD

**Issue by stlweb** [danielhrisca/asammdf#311]
# Python version
('python=3.8.1 (tags/v3.8.1:1b293b6, Dec 18 2019, 23:11:46) [MSC v.1916 64 bit '
 '(AMD64)]')
'os=Windows-10-10.0.17134-SP0'
'numpy=1.18.1'
'asammdf=5.17.3'

  ## MDF version
  4.10

  ## Code snippet
  GUI
  
# Description

If I want to compare Signals with text_values the plot shows straight lines with and without "ignore value2text conversion"
In single file mode a plot of the same signals with active option"ignore value2text conversion" 
lead to the expected result, with inactive option "ignore value2text conversion" i get the same result (straigth lines) as in comparison mode.

It seems that comparison mode ignores the ignore option "value2text conversion".

**Comment by danielhrisca** [comment]
@stlweb please check the development branch code

**Comment by stlweb** [comment]
@danielhrisca the ignore_value2text_conversion is working in comparison mode. Thanks, you can close the issue.

Is there any chance to get y-axis with text-values in the future?

**Comment by danielhrisca** [comment]
> Is there any chance to get y-axis with text-values in the future?

This needs some refactoring since ignore_value2text_conversion completely ignore the conversion, hence there is no way to access the text description, and the second point is that the plotted channels are converted to physical values, and in this case you would see the text labels but the plot will use an all-0 channel
