### ISSUE TITLE
Asammdf installation failed due to cchardet version restrictions

### ISSUE THREAD

**Issue by Lama09** [danielhrisca/asammdf#427]
# Python version
3.8
## MDF version
5.23.1
  
I did setup a new python environment for python 3.8 and tried to install asammdf. This will failed due to cchardet version restrictions. Would it be possible to change the settings in your setup.py file to 

`"cChardet>=2.1.5"`

On my distribution is the latest version 2.1.6 installed. The setuptools tries to downgrade to 2.1.5, put this will fail while creating the wheel file due to version restrictions of the C++ compiler.

```
ERROR: Failed building wheel for cChardet
Microsoft Visual C++ 14.0 or greater is required

```

**Comment by danielhrisca** [comment]
@Lama09 can you install the c++ compiler? 
cChardet 2.1.6 has a dll problem (see #341)

**Comment by a543c23** [comment]
I encountered the same problem. I solved by changing the requirements manually to >=2.1.5
Also with me, install of cchardet 2.1.5 will fail (also when installing separately) because the wheel cannot be built. Also, there is no matching precompiled wheel in the repository.
Using Windows 7 64bit, Python 3.8 64bit

**Comment by danielhrisca** [comment]
`cChardet` is now optional (development branch). Additionally you can also have `chardet` installed and this will be used with priority

**Comment by a543c23** [comment]
Thank you for quickly changing the dependencies. I further stepped into the problem, because I also could not compile the development branch.
The problem was related to io.h not found by Visual C++ Compiler. This issue appeared for many people using python and also specifically cchardet.
There are multiple ways to solve the compiler problem. It seems to be related to faulty installation of Visual Studio Build Tools 2019 and universal CRT. In my case, the Windows SDK 7.1 is installed in parallel and that seems to cause the problem.

[https://www.xspdf.com/help/52577556.html](url)
[https://devblogs.microsoft.com/cppblog/introducing-the-universal-crt/](url)
[https://stackoverflow.com/questions/12460307/installation-of-visual-studio-2010-any-edition-installs-only-2-files-in-the-c](url)
[https://stackoverflow.com/questions/40018405/cannot-open-include-file-io-h-no-such-file-or-directory](url)

For me, setting the following environment variables worked:

`set INCLUDE=C:\Program Files (x86)\Windows Kits\10\Include\10.0.18362.0\ucrt;C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.28.29333\include;C:\Program Files (x86)\Windows Kits\10\Include\10.0.18362.0\shared;C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.28.29333\lib\onecore\x64;C:\Program Files (x86)\Microsoft Visual Studio 10.0\VC\lib\amd64;C:\Program Files (x86)\Windows Kits\10\bin\10.0.18362.0\x64`

`set LIB=C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.28.29333\lib\onecore\x64;C:\Program Files (x86)\Microsoft Visual Studio 10.0\VC\lib\amd64;C:\Program Files (x86)\Windows Kits\10\Lib\10.0.18362.0\um\x64;C:\Program Files (x86)\Windows Kits\10\Lib\10.0.18362.0\um\x64;C:\Program Files (x86)\Windows Kits\10\Lib\10.0.18362.0\ucrt\x64`

`set PATH=%PATH%;C:\Program Files (x86)\Windows Kits\10\bin\10.0.18362.0\x64`

You will have to adjust the directories to match your installation.

If somebody needs the compiled wheel for Windows x64 and Python 3.8 for cchardet 2.1.5, please find it here:
[cchardet-2.1.5-cp38-cp38-win_amd64.zip](https://github.com/danielhrisca/asammdf/files/5560782/cchardet-2.1.5-cp38-cp38-win_amd64.zip)
wheel size=114953 
sha256=8c41ab6068417de7d4ccfd1845256de2035d12c611aa99a2f46f36b5697b8243

**Comment by danielhrisca** [comment]
> `cChardet` is now optional (development branch). Additionally you can also have `chardet` installed and this will be used with priority

I've been reminded today why cChardet was the default: it is orders of magnitude faster than chardet on large files (tens of MB). For this reason cChardet will be used with priority if it is installed.

**Comment by danielhrisca** [comment]
release 6.0.0 is available
