### ISSUE TITLE
the acq_name of channel group changed after applying .filter() function

### ISSUE THREAD

**Issue by Yuanli-Liu** [danielhrisca/asammdf#430]
# Python version
```python
('python=3.8.5 | packaged by conda-forge | (default, Aug 29 2020, 01:22:49) \n'
 '[GCC 7.5.0]')
'os=Linux-5.4.0-52-generic-x86_64-with-glibc2.10'
'numpy=1.19.1'
'asammdf=5.22.0'
```
# Code 

  ## MDF version
4.10

  ## Code snippet
    mf4_reader = MDF("test.mf4")
    # channels_namelist is a list of channel name
    mf4_reader = mf4_reader.filter(channels_namelist)
    for idx, gitem in enumerate(mf4_reader.groups):
        cg = gitem["channel_group"]
        acq_name = cg.acq_name
        print(idx, cg.acq_name, sep="=>")
  
# Description

If we comment line2:` mf4_reader.filter(channels_namelist)`, the output is normal. Otherwise, the output of **acq_name** are abnormal and most of them are empty.

**Comment by Yuanli-Liu** [comment]
```

```

**Comment by Yuanli-Liu** [comment]
Similarly, after calling `.filter()`, the output of `print(mdf.header.comment)` is empty.

**Comment by JulienGrv** [comment]
It's because `.filter()` returns a new MDF object and you overwrite the original one in your code snippet. Regarding channel groups acq_name, if you use the development branch, I made changes and now channel groups acq_name are conserved after `.filter()`.

Either you wait until next release or you can already try the development branch like this:
`pip install git+https://github.com/danielhrisca/asammdf.git@development`

Your code could then look like this:

```python
mf4_reader = MDF("test.mf4")
# channels_namelist is a list of channel name
mf4_reader_filtered = mf4_reader.filter(channels_namelist)
print(mf4_reader.header.comment)
for idx, gitem in enumerate(mf4_reader_filtered.groups):
    cg = gitem["channel_group"]
    acq_name = cg.acq_name
    print(idx, cg.acq_name, sep="=>")
```

**Comment by Yuanli-Liu** [comment]
Thank you for your answer sincerely！:tada:
