### ISSUE TITLE
Feature Request: Only read first occurrence of signal

### ISSUE THREAD

**Issue by thomasfiala** [danielhrisca/asammdf#571]
# Description

I mostly have data files that show multiple entries of the same signal name. It would be a great help if I have the option to automatically select only the first occurrence of the signal when reading the data file.

'python=3.7.10 (default, Feb 26 2021, 13:06:18) [MSC v.1916 64 bit (AMD64)]'
'os=Windows-10-10.0.18362-SP0'
'numpy=1.20.1'
'asammdf=6.3.0'

**Comment by JulienGrv** [comment]
There is already such an option, see [here](https://github.com/danielhrisca/asammdf/issues/568#issuecomment-919409434) but before you start using it right if you're using the library to calculate KPI, it's risky to go with this solution as you could read data that is not the one you were expecting. That's why I suggest you the second solution which is to disambiguate; look at my example [here](https://github.com/danielhrisca/asammdf/issues/568#issuecomment-920628130).

**Comment by thomasfiala** [comment]
Yes, I know that it's risky. That's why I don't ask for such a behavior to be the default setting.

Currently, I make use of this command a lot:
`mdf.get(signal_name, *mdf.whereis(signal_name)[0])`

However, it would be a lot faster if the signal was not loaded in the first place when reading the mdf file. I think that if there is an option that is well documented and the risk is clearly addressed, this would be a nice feature.

**Comment by JulienGrv** [comment]
I am not sure if this is what you are looking for but there is an option to filter channels on loading in the MDF constructor function named 'channels'. See [here](https://asammdf.readthedocs.io/en/latest/api.html#asammdf.mdf.MDF)

**Comment by thomasfiala** [comment]
The 'channels' option is a great feature. However, currently all instances with the same signal name are read in.
What I basically ask for is an implementation of the `raise_on_multiple_occurrences` feature within the constructor. If only the first occurrence of each signal name was read in, you wouldn't have to use this setting afterwards.

**Comment by JulienGrv** [comment]
Ok things are clear now from my side. I can't tell you if and when it will be implemented though

**Comment by thomasfiala** [comment]
Great, Thanks!
