### ISSUE TITLE
can not install asammdf on ubuntu

### ISSUE THREAD

**Issue by yozdas** [danielhrisca/asammdf#655]
# Python version
'python=3.10.2 (main, Jan 15 2022, 18:02:07) [GCC 9.3.0]'
'os=Linux-5.4.0-97-generic-x86_64-with-glibc2.31'
'numpy=1.22.2'

# Linux release
Distributor ID:	Ubuntu
Description:	Ubuntu 20.04.3 LTS
Release:	20.04
Codename:	focal

# Description

Can not install asammdf on Ubuntu, it produces error like;
**ERROR: Could not build wheels for asammdf, which is required to install pyproject.toml-based projects**
please check the error file attached
[asammdf_error.txt](https://github.com/danielhrisca/asammdf/files/8054559/asammdf_error.txt)

**Comment by JulienGrv** [comment]
I am not sure but I think you need to install python3-dev

**Comment by yozdas** [comment]
> I am not sure but I think you need to install python3-dev with apt
didn't work for me, thanks for trying help.

**Comment by JulienGrv** [comment]
Your issue is not directly related to asammdf but to your environment. Pip is not able to compile c extensions because it cannot find the python headset file Python.h. See this [Stack Overflow discussion](https://stackoverflow.com/questions/21530577/fatal-error-python-h-no-such-file-or-directory#21530768) for help.

Since you have Python version 3.10, maybe you need to apt install python3.10-dev or apt install libpython3.10-dev. I am not using Ubuntu so I am guessing here

**Comment by danielhrisca** [comment]
You could also try after installing ``libpython3.10-dev``
