### ISSUE TITLE
Incorrect start_time property due to datetime local conversion

### ISSUE THREAD

**Issue by hhalaby** [danielhrisca/asammdf#675]
# Python version
_Please run the following snippet and write the output here_
```python
import platform
import sys
from pprint import pprint

pprint("python=" + sys.version)
pprint("os=" + platform.platform())

try:
    import numpy
    pprint("numpy=" + numpy.__version__)
except ImportError:
    pass

try:
    import asammdf
    pprint("asammdf=" + asammdf.__version__)
except ImportError:
    pass
```

```
('python=3.9.7 (tags/v3.9.7:1016ef3, Aug 30 2021, 20:19:38) [MSC v.1929 64 bit '
 '(AMD64)]')
'os=Windows-10-10.0.19044-SP0'
'numpy=1.22.2'
ldf is not supported
xls is not supported
xlsx is not supported
yaml is not supported
'asammdf=7.0.7'
```

# Code 

  ## MDF version
4.10

  ## Code snippet
` mdf_file.to_dataframe(SIGNAL_NAME, time_as_date=True)`
  
  ## Traceback
NO TRACEBACK
  
# Description

The start_time property of the mdf file seems to be incorrect and the zone conversion applied twice.
If the GPS signal, for example, shows 9 AM UTC, the to_dataframe method which uses the start_time property gives out timestamps at 11 AM UTC+1. We know this to be incorrect because we also manually log the time at which the vehicle is driven (10 AM in this example).

We have seen this for 5 vehicles with 4000+ mdf files. 

The vehicles are equipped with Vector Loggers GL2400 configured to Paris Time (UTC+1 at the time of the data recording campaign).

Maybe it has to do with how the start_time property is calculated ?

This is the metadata of the file in the example:
![image](https://user-images.githubusercontent.com/86954225/160178358-7c73ed2b-b9b7-43ff-ae1e-377df252d66c.png)

Please do not hesitate to ask for any additional information that might help
Issue #389 might be related but I'm not sure
Thanks a lot!

**Comment by danielhrisca** [comment]
Please send the output of this code

```python
with open(mf4file, 'rb') as f:
    print(f.read(168).hex())
```

**Comment by hhalaby** [comment]
Here's the output

`4d44462020202020342e313020202020616d646637303700000000009a010000000000000000000000000000000000000000000000000000000000000000000023234844000000006800000000000000060000000000000050f374130000000018f3741300000000000000000000000000000000000000000000000000000000a80000000000000000e4ae29b3ead916000000000100000000000000000000000000000000000000`

**Comment by danielhrisca** [comment]
Hello,

loading the file in Vector MDFValidator shows a completely different time on my PC (my local time is UTC+2)

![image](https://user-images.githubusercontent.com/20952040/160283819-9d0e615a-0d70-43f7-a27b-079ada45938c.png)

and in asammdf gui another value

![image](https://user-images.githubusercontent.com/20952040/160283994-c6eba87e-4991-4f46-9639-9aa025ab3a0a.png)

The problem is that the timestamp is set as local time, so when you load the file you will se different values depending on the PC's local time.

**Comment by danielhrisca** [comment]
@zhoubo-lab @hhalaby @MatinF 
please try out the latest development branch code regarding the datetime issues

**Comment by hhalaby** [comment]
Hello Daniel,

The hex output I gave you was in fact for a different file, I apologize for the confusion. This does not affect the issue at hand and I will summarize all the info so far using, as an example, the file corresponding to the hex output I gave you:

- The GNSS signal for the file shows 21:19:54 UTC at the measurement start 
![image](https://user-images.githubusercontent.com/86954225/160450862-7fcddb6e-1ffc-4f52-a712-09d43ac00211.png)

- since the Vector Logger is configured to Paris time, measurement start is written as 22:19:54 by Vector. 
![image](https://user-images.githubusercontent.com/86954225/160437665-12cd7836-0a01-4811-8c99-c6905f7d664a.png)

### With asammdf Version 7.07 (main branch, installed with PyPI)
- when we import the mdf file in Python, the start time is written as 23:19:54 without UTC information shown which is wrong because 22:19:54 was already at UTC +1 and so another conversion was not needed
![image](https://user-images.githubusercontent.com/86954225/160450011-624a1335-d024-4f3a-bb00-0b5cd9e050f3.png)

-  when we use the `to_dataframe ` method with `time_as_date=True` the given output is 00:19:54 today (instead of the previous 23:19 because Paris is since then UTC+2). This is doubly wrong because we apply a +1h conversion on top of the converted start time.
![image](https://user-images.githubusercontent.com/86954225/160449968-48391bda-6bba-4b65-a572-150cf1285089.png)


### With asammdf development branch
- when we import the mdf file in Python, the start time is written as 23:19:54 with UTC+1 which is better because UTC information is shown but it is still wrong because 22:19:54 was already at UTC +1 and so another conversion was not needed.
![image](https://user-images.githubusercontent.com/86954225/160451220-2deae747-d88e-450d-8668-addecfb9dff9.png)

-  when we use the `to_dataframe ` method with `time_as_date=True` the given output is 01:19:54 today which is also wrong because we applying a +2h conversion on top of the already extra +2h conversion.
![image](https://user-images.githubusercontent.com/86954225/160451472-6879b611-1ce1-4232-80ca-9aef3f66858c.png)

I believe there are 3 issues:

- start time parsing assumes UTC for the start time information
- there's a double conversion with the to_dataframe method
- the development branch isn't taking into account that Paris was +1h at the start time and thus applies a +2h conversion (this issue I believe isn't present in the main branch?)


If I may suggest a solution that seems adequate: add the possibility to set the UTC information for start time parsing ?

**Comment by danielhrisca** [comment]
Please send the snippet output with the correct file

**Comment by danielhrisca** [comment]
You are wright that my fixes did not touch the ``to_dataframe`` method. Please try again now

**Comment by hhalaby** [comment]
[example_mdf.zip](https://github.com/danielhrisca/asammdf/files/8365038/example_mdf.zip)
This is the file I detailed above. 
I scrambled text and exported the relevant channel group. You can use the file freely.

The snippet:

`4d44462020202020342e313020202020616d646637303700000000009a010000000000000000000000000000000000000000000000000000000000000000000023234844000000006800000000000000060000000000000050f374130000000018f3741300000000000000000000000000000000000000000000000000000000a80000000000000000e4ae29b3ead916000000000100000000000000000000000000000000000000`

**Comment by danielhrisca** [comment]
> [example_mdf.zip](https://github.com/danielhrisca/asammdf/files/8365038/example_mdf.zip) This is the file I detailed above. I scrambled text and exported the relevant channel group. You can use the file freely.
> 
> The snippet:
> 
> `4d44462020202020342e313020202020616d646637303700000000009a010000000000000000000000000000000000000000000000000000000000000000000023234844000000006800000000000000060000000000000050f374130000000018f3741300000000000000000000000000000000000000000000000000000000a80000000000000000e4ae29b3ead916000000000100000000000000000000000000000000000000`

There is no sample in the file so I cannot check the dataframe

**Comment by hhalaby** [comment]
[example_mdf.zip](https://github.com/danielhrisca/asammdf/files/8365124/example_mdf.zip)
This should be good

**Comment by danielhrisca** [comment]
![image](https://user-images.githubusercontent.com/20952040/160459658-b9fa2633-3fdb-447f-ada5-acefbd874a17.png)
![image](https://user-images.githubusercontent.com/20952040/160459727-154110b4-e18c-4f11-805f-235436cd2bee.png)
![image](https://user-images.githubusercontent.com/20952040/160459814-5303b46d-ae6e-41ce-8183-31d71d15ebc5.png)

The time stamp is set as local PC in the file so all that can be done is to assume the time zone of the PC were the measurement is loaded with asammdf. The timestamp in the screenshots is OK for my time zone.

**Comment by hhalaby** [comment]
Would it be possible to set the UTC information for the start time property when reading an MF4 file?

 This way we can specify that 22:19:54 is actually UTC+1 and the timestamps in the dataframe would be correct. Because otherwise the start time property is wrongly assumed to be UTC.

**Comment by danielhrisca** [comment]
You can overwrite the start_time attribute


```python
mdf.header.start_time = my_datetime_value
```

**Comment by hhalaby** [comment]
This is an acceptable workaround. Thanks

**Comment by chr-sy** [comment]
I think there is another problem with start times which renders this function kind of broken.

The problem occurs for cases with hd_time_flags=1 (i.e. "local time") set.

According to the MDF spec, activating this bit means that "the start time stamp in nanoseconds represents the local time instead of the UTC time".
In contrast, asammdf produces the respective value (HeaderBlock.abs_time) by means of the datetime.datetime.timestamp() function (within the start_time setter function). This function produces an UTC timestamp (i.e. ns from Unix epoch in UTC) from the start time (which contradicts the MDF spec!)
During asammdf read, this value is processed via the datetime.datetime.fromtimestamp() function, which takes UTC timestamps and converts the resulting datetime to the local time zone.

Thus, times are processed correctly as long as you only use asammdf for read and write operations. Problems arise once you read files generated from 3rd party tools with asammdf. If these tools implement the MDF spec correctly, they write "local" timestamps to the file, which are interpreted as UTC timestamps by asammdf (or rather the underlying standard libs). As a result, time zone differences are added twice resulting in wrong times (as can be seen in the screenshots above).


Now how to resolve this issue?

I'd suggest to add some simple steps for cases with hd_time_flags=1:
1. start_time setter should interpret all times as UTC (i.e. replace the tzinfo by utc without conversion so that it is not converted automatically) before calling the timestamp() function. 
2. start_time getter should call the fromtimestamp() function with parameter tz=utc and replace the tzinfo of the resulting datetime by the local timezone without conversion.

**Comment by danielhrisca** [comment]
@chr-sy @hhalaby 
please try the development branch code

**Comment by hhalaby** [comment]
Hello, thanks for the heads-up. I'm no longer working on this project.
