### ISSUE TITLE
DBC file and negative values

### ISSUE THREAD

**Issue by n10n-n10n** [danielhrisca/asammdf#964]
# Python version
('python=3.9.13 (main, May 24 2022, 21:28:44) \n'
 '[Clang 13.0.0 (clang-1300.0.29.30)]')
'os=macOS-13.6-x86_64-i386-64bit'
'numpy=1.24.3'
ldf is not supported
xls is not supported
xlsx is not supported
'asammdf=7.3.17'
# Code 

  ## MDF version
  N/A - generated MDF file

  ## Code snippet
 ```python
import numpy
from asammdf import MDF
from asammdf import Signal
from asammdf.blocks.source_utils import Source

types = [
    ('CAN_DataFrame.BusChannel', 'u1'),
    ('CAN_DataFrame.ID', '<u2'),
    ('CAN_DataFrame.IDE', 'u1'),
    ('CAN_DataFrame.DLC', 'u1'),
    ('CAN_DataFrame.DataLength', 'u1'),
    ('CAN_DataFrame.DataBytes', 'u1', (8,)),
    ('CAN_DataFrame.Dir', 'u1')
]

frame = [
    [0x01],   # BusChannel
    [0x7E8],  # Response PID
    [0x00],   # IDE
    [0x08],   # DLC
    [0x08],   # DataLength
    [[0x05, 0x62, 0x44, 0xD2, 0xFF, 0xC4, 0xAA, 0xAA]],   # DataBytes
    [0x00]    # Dir
]

src = Source(
    source_type=Source.SOURCE_BUS,
    bus_type=Source.BUS_TYPE_CAN,
    name="CAN1",
    path="CAN1",
    comment="CAN1")
sig = Signal(
    numpy.core.records.fromarrays(frame, numpy.dtype(types)),
    [numpy.datetime64()],
    name = 'CAN_DataFrame',
    comment = 'CAN1',
    raw = False,
    source = src
)

mdf = MDF(version = '4.10')
mdf.append([sig], comment='CAN_DataFrame', common_timebase=True)
mdf = mdf.extract_bus_logging(database_files = { 'CAN': [ ('issue.dbc',0) ], "LIN": []})

for ch in mdf.iter_channels():
    if ch.name.startswith('fuel_temperature'):
        print('{0}: {1}'.format(ch.name, ch.samples))
``` 

  ## Traceback
  N/A - no errors are thrown
  
# Description

Having a DBC file as below, referred to as 'issue.dbc' in the code section:
```
BO_ 2024 Responses_7E8: 8 Vector__XXX
	SG_ MultiplexIndexSignal M : 15|24@0+ (1,0) [0|0] "" Vector__XXX
	SG_ fuel_temperature_1 m6440146 : 39|16@0+ (0.1,0) [-100|100] "C" 0x6244D2
	SG_ fuel_temperature_2 m6440146 : 39|16@0- (0.1,0) [-100|100] "C" 0x6244D2
	SG_ fuel_temperature_3 m6440146 : 38|15@0- (0.1,0) [-100|100] "C" 0x6244D2
```

The snippet outputs the following: 
```
fuel_temperature_1: [6547.6]
fuel_temperature_2: [-1510.5]
fuel_temperature_3: [-6.]
```

The data extracted by DBC file is 16-bit signed integer starting from bit 39: 0xFFC4. It's extracted three times - `fuel_temperature_1`as unsigned integer, `fuel_temperature_2` as signed and `fuel_temperature_3` as signed but offset by 1 bit and only 15 bits of length.

Correct representation of 0xFFC4 as signed decimal is -60, hence -6.0 should be the correct result from DBC conversion minding the scaling and offset.

`fuel_temperature_1` gives a correct result for unsigned integer - thus validating start bit and length

`fuel_temperature_2` yields a clearly incorrect result - while the result is negative it's value is out of reasonable ranges. 

`fuel_temperature_3` yields correct looking result but has incorrect start bit in DBC and loses 1 bit of resolution.

**Comment by danielhrisca** [comment]
@n10n-n10n please try the development branch code

**Comment by n10n-n10n** [comment]
@danielhrisca thank you!

Development branch seems to fix the issue both for the above simple test case as well as multitude of my actual metrics - I think we can call this case closed. 

```
$ pip show asammdf | grep Version
Version: 7.3.19.dev7

$ python3 issue.py 
fuel_temperature_1: [6547.6]
fuel_temperature_2: [-6.]
fuel_temperature_3: [-6.]
```

**Comment by TiHONGTONG** [comment]
@n10n-n10n please try the development branch code   what mean？？？

**Comment by danielhrisca** [comment]
pip install https://github.com/danielhrisca/asammdf/achive/development.zip

**Comment by TiHONGTONG** [comment]
not0439@DZ-NOT-0439:~/下载/asammdf$ git branch
* development
  master
not0439@DZ-NOT-0439:~/下载/asammdf$ pip install .
Defaulting to user installation because normal site-packages is not writeable
Processing /home/not0439/下载/asammdf
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Requirement already satisfied: numexpr in /home/not0439/.local/lib/python3.10/site-packages (from asammdf==8.0.1.dev1) (2.10.1)
Requirement already satisfied: lxml>=4.9.3 in /home/not0439/.local/lib/python3.10/site-packages (from asammdf==8.0.1.dev1) (5.3.0)
Requirement already satisfied: typing-extensions in /home/not0439/.local/lib/python3.10/site-packages (from asammdf==8.0.1.dev1) (4.12.2)
Requirement already satisfied: canmatrix[arxml,dbc]>=1.0 in /home/not0439/.local/lib/python3.10/site-packages (from asammdf==8.0.1.dev1) (1.0)
Requirement already satisfied: python-dateutil in /home/not0439/.local/lib/python3.10/site-packages (from asammdf==8.0.1.dev1) (2.9.0.post0)
Requirement already satisfied: numpy<2.0.0,>=1.23.0 in /home/not0439/.local/lib/python3.10/site-packages (from asammdf==8.0.1.dev1) (1.23.5)
Requirement already satisfied: pandas in /home/not0439/.local/lib/python3.10/site-packages (from asammdf==8.0.1.dev1) (2.2.2)
Requirement already satisfied: isal in /home/not0439/.local/lib/python3.10/site-packages (from asammdf==8.0.1.dev1) (1.7.0)
Requirement already satisfied: lz4 in /home/not0439/.local/lib/python3.10/site-packages (from asammdf==8.0.1.dev1) (4.3.3)
Requirement already satisfied: click in /usr/lib/python3/dist-packages (from canmatrix[arxml,dbc]>=1.0->asammdf==8.0.1.dev1) (8.0.3)
Requirement already satisfied: future in /usr/lib/python3/dist-packages (from canmatrix[arxml,dbc]>=1.0->asammdf==8.0.1.dev1) (0.18.2)
Requirement already satisfied: six in /usr/lib/python3/dist-packages (from canmatrix[arxml,dbc]>=1.0->asammdf==8.0.1.dev1) (1.16.0)
Requirement already satisfied: attrs>=19.2.0 in /home/not0439/.local/lib/python3.10/site-packages (from canmatrix[arxml,dbc]>=1.0->asammdf==8.0.1.dev1) (24.2.0)
Requirement already satisfied: tzdata>=2022.7 in /home/not0439/.local/lib/python3.10/site-packages (from pandas->asammdf==8.0.1.dev1) (2024.1)
Requirement already satisfied: pytz>=2020.1 in /usr/lib/python3/dist-packages (from pandas->asammdf==8.0.1.dev1) (2022.1)
Building wheels for collected packages: asammdf
  Building wheel for asammdf (pyproject.toml) ... done
  Created wheel for asammdf: filename=asammdf-8.0.1.dev1-cp310-cp310-linux_x86_64.whl size=913978 sha256=2cca22f0eea564dee5fd907e304403141ef82b9f0895a44c4c2aa8c73a14f9a4
  Stored in directory: /tmp/pip-ephem-wheel-cache-xal_mzr_/wheels/bf/6e/cf/b6f59b3d5d7ca89b7a9f0994b6f0dd8f401e91ed27efddd420
Successfully built asammdf
Installing collected packages: asammdf
Successfully installed asammdf-8.0.1.dev1
not0439@DZ-NOT-0439:~/下载/asammdf$ asammdf
ldf is not supported
xls is not supported
xlsx is not supported
qt.qpa.plugin: Could not load the Qt platform plugin "xcb" in "" even though it was found.
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: minimal, vnc, xcb, minimalegl, eglfs, offscreen, wayland, wayland-egl, vkkhrdisplay, linuxfb.

**Comment by TiHONGTONG** [comment]
branch development still error
